version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/feckmore/my-first-circle
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: echo "My first CicleCI"

workflows:
  version: 2
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test
