version: 2
jobs:
  test:
    working_directory: /go/src/github.com/feckmore/my-first-circle
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build:
    working_directory: /go/src/github.com/feckmore/my-first-circle
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Build lambda functions
          command: make build
  deploy:
    working_directory: /go/src/github.com/feckmore/my-first-circle
    docker:
      - image: circleci/node:10.15.0
    steps:
      - run: echo Key value from circle context=${MY_KEY_NAME}
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - run: curl -O https://storage.googleapis.com/golang/go1.9.1.linux-amd64.tar.gz
      - run: tar -C /usr/local -xzf go1.9.1.linux-amd64.tar.gz
      - run: export PATH="/usr/local/go/bin:$PATH"
      - run: sls version
      - run: go version
      - run:
          name: Build lambda functions
          command: make build
      # - run:
      #     name: Deploy lambda functions
      # command: make deploy

workflows:
  version: 2
  test_build:
    jobs:
      - test
      - build
      - deploy:
          context: org-global
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - master
