version: 2
jobs:
  test:
    working_directory: /go/src/github.com/feckmore/my-first-circle
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build:
    working_directory: /go/src/github.com/feckmore/my-first-circle
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Build lambda functions
          command: make build
  deploy:
    working_directory: /go/src/github.com/feckmore/my-first-circle
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: echo "DEPLOY"

workflows:
  version: 2
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - build
